version: '3.7'

services:
  openvpn:
    image: defn/openvpn
    env_file: .env
    cap_add:
    - NET_ADMIN
    ports:
    - ${OPENVPN_IP}:1194:1194
    volumes:
    - ${OPENVPN_MOUNT}/openvpn:/etc/openvpn
    restart: always
