#!/usr/bin/env bash

function main {
  rm -f ovpn_env.sh openvpn.conf

  ovpn_genconfig -u tcp://169.254.1.1

  perl -pe 's{^(#*\s*push\s+.*)$}{}i' -i openvpn.conf

  (
    echo comp-lzo no
    echo "push \"comp-lzo no\""

    echo "push \"dhcp-option DNS 169.254.1.1\""
    echo "push \"dhcp-option DOMAIN-SEARCH kube-system.svc.cluster.local\""
    echo "push \"dhcp-option DOMAIN-SEARCH default.svc.cluster.local\""
  ) >> openvpn.conf
}

main "$@"
