#!/usr/bin/env bash

function main {
  local nm_account="$1"; shift

  set -exfu

  cd /etc/openvpn

  "$0.expect" "${nm_account}" "$@"

  {
    ovpn_getclient "${nm_account}" combined
    echo redirect-gateway !ipv4
  } > "${nm_account}.ovpn"

  mkdir -p ccd
  {
    echo "push \"route 172.17.0.0 255.255.0.0\""
    echo "push \"route 10.70.0.0 255.255.0.0\""
    echo "push \"route 10.71.0.0 255.255.0.0\""
  } > "ccd/${nm_account}"
}

main "$@"
